--- drivers/input/touchscreen/Makefile
+++ drivers/input/touchscreen/Makefile
@@ -39,6 +40,14 @@ obj-$(CONFIG_TOUCHSCREEN_EGALAX)	+= egalax_ts.o
 obj-$(CONFIG_TOUCHSCREEN_FT6236)	+= ft6236.o
 obj-$(CONFIG_TOUCHSCREEN_FUJITSU)	+= fujitsu_ts.o
 obj-$(CONFIG_TOUCHSCREEN_GOODIX)	+= goodix.o
+obj-$(CONFIG_TOUCHSCREEN_GSLX680A)      += gslx680a.o gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GSLX680_D708)	+= gslx680_d708/ gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GSLX680_PAD)	+= gslx680_pad.o gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GSLX680_VR)	+= gslx680.o gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GSLX680_FIREFLY)	+= gslx680_firefly.o gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GSL3673)	+= gsl3673.o gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GSL3673_800X1280)	+= gsl3673_800x1280.o gsl_point_id.o
+obj-$(CONFIG_TOUCHSCREEN_GT9XX)		+= gt9xx/
 obj-$(CONFIG_TOUCHSCREEN_ILI210X)	+= ili210x.o
 obj-$(CONFIG_TOUCHSCREEN_IMX6UL_TSC)	+= imx6ul_tsc.o
 obj-$(CONFIG_TOUCHSCREEN_INEXIO)	+= inexio.o
