--- arch/arm64/include/asm/Kbuild
+++ arch/arm64/include/asm/Kbuild
@@ -36,7 +36,6 @@ generic-y += poll.h
 generic-y += preempt.h
 generic-y += resource.h
 generic-y += rwsem.h
-generic-y += sections.h
 generic-y += segment.h
 generic-y += sembuf.h
 generic-y += serial.h
