--- arch/arm/boot/dts/Makefile
+++ arch/arm/boot/dts/Makefile
@@ -512,22 +512,80 @@ dtb-$(CONFIG_ARCH_QCOM) += \
 dtb-$(CONFIG_ARCH_REALVIEW) += \
 	arm-realview-pb1176.dtb
 dtb-$(CONFIG_ARCH_ROCKCHIP) += \
+	px3se-evb.dtb \
+	rk3036-echo.dtb \
+	rk3036-evb.dtb \
+	rk3036-kylin.dtb \
 	rk3066a-bqcurie2.dtb \
 	rk3066a-marsboard.dtb \
 	rk3066a-rayeager.dtb \
+	rk3126-bnd-d708.dtb \
+	rk3126-bnd-d708-avb.dtb \
+	rk3126-bnd-m88-emmc.dtb \
+	rk3126-evb.dtb \
+	rk3126-linux.dtb \
+	rk3128-fireprime.dtb \
+	rk3128h-box.dtb \
+	rk3128h-box-avb.dtb \
+	rk3128h-evb-linux.dtb \
 	rk3188-radxarock.dtb \
+	rk3228-evb.dtb \
+	rk3229-at-3nod.dtb \
+	rk3229-at-3nod-func.dtb \
+	rk3229-at-gva.dtb \
+	rk3229-echo-v10.dtb \
+	rk3229-evb.dtb \
+	rk3229-evb-android.dtb \
+	rk3229-evb-android-avb.dts \
+	rk3229-gva-sdk.dtb \
 	rk3288-evb-act8846.dtb \
+	rk3288-evb-android-act8846-edp.dtb \
+	rk3288-evb-android-rk808-edp.dtb \
+	rk3288-evb-android-rk808-edp-avb.dtb \
+	rk3288-evb-android-rk818-edp.dtb \
+	rk3288-evb-android-rk818-hdmi.dtb \
+	rk3288-evb-android-rk818-lvds.dtb \
+	rk3288-evb-android-rk818-mipi.dtb \
+	rk3288-evb-android-rk818-mipi-edp.dtb \
+	rk3288-evb-rk1608.dtb \
 	rk3288-evb-rk808.dtb \
+	rk3288-evb-rk808-linux.dtb \
+	rk3288-fennec.dtb \
 	rk3288-firefly-beta.dtb \
+	rk3288-firefly-reload.dtb \
+	rk3288-firefly-reload-linux.dtb \
+	rk3288-firefly-rk808.dtb \
 	rk3288-firefly.dtb \
+	rk3288-miniarm.dtb \
+	rk3288-miqi.dtb \
+	rk3288-phycore-rdk.dtb \
 	rk3288-popmetal.dtb \
+	rk3288-popmetal-android.dtb \
+	rk3288-popmetal-android-vga.dtb \
 	rk3288-r89.dtb \
 	rk3288-rock2-square.dtb \
+	rk3288-th804.dtb \
+	rk3288-th804-avb.dtb \
 	rk3288-veyron-jaq.dtb \
 	rk3288-veyron-jerry.dtb \
 	rk3288-veyron-minnie.dtb \
 	rk3288-veyron-pinky.dtb \
-	rk3288-veyron-speedy.dtb
+	rk3288-veyron-speedy.dtb \
+	rk3288-x7811-rk818-dual-dsi.dtb \
+	rk3308-dot-v10-aarch32.dtb \
+	rk3308-dot-rk816-v10-aarch32.dtb \
+	rk3308-evb-dmic-i2s-v10-aarch32.dtb \
+	rk3308-evb-dmic-pdm-v11-aarch32.dtb \
+	rk3308-voice-module-board-v10-aarch32.dtb \
+	rk3308-voice-module-board-v11-aarch32.dtb \
+	rk3308-voice-module-amic-mainboard-v10-aarch32.dtb \
+	rk3308-voice-module-pdm-mainboard-v10-aarch32.dtb \
+	rk3308b-evb-amic-v10-aarch32.dtb \
+	rk3326-evb-lp3-v10.dtb \
+	rk3326-863-lp3-v10.dtb \
+	rk3326-evb-lp3-v10-avb.dtb \
+	rk3326-863-lp3-v10-avb.dtb \
+	rv1108-minievb-v10.dtb
 dtb-$(CONFIG_ARCH_S3C24XX) += \
 	s3c2416-smdk2416.dtb
 dtb-$(CONFIG_ARCH_S3C64XX) += \
@@ -782,5 +840,15 @@ endif
 dtstree		:= $(srctree)/$(src)
 dtb-$(CONFIG_OF_ALL_DTBS) := $(patsubst $(dtstree)/%.dts,%.dtb, $(wildcard $(dtstree)/*.dts))
 
-always		:= $(dtb-y)
+DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
+ifneq ($(DTB_NAMES),)
+DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
+else
+DTB_LIST := $(dtb-y)
+endif
+
+targets += dtbs dtbs_install
+targets += $(DTB_LIST)
+
+always		:= $(DTB_LIST)
 clean-files	:= *.dtb
